"""
extract_strategy_data.py
------------------------------------------------------------
The data engine. Run this on your own machine (it needs internet
access to FastF1's data source, which isn't available from inside
this chat). It pulls real session data for a race, boils it down to
four numbers per race, and writes them into data/races.json so the
front end can do the rest of the math instantly in the browser.

Usage:
    pip install fastf1 pandas
    python extract_strategy_data.py

What it computes, per race:
    pitLoss      -> median time lost during a pit stop at this circuit
    degPerLap    -> slope of lap time vs tyre age (seconds lost per lap)
    initialGap   -> the gap between the two drivers right before the
                    pit window opens
    rivalPitLap  -> the lap the leading car actually pitted on

This intentionally does NOT try to be a general-purpose race analysis
tool. It only extracts the handful of numbers the front-end simulator
needs - keeping the scope tight is what makes the JSON output stay
clean and the front end stay fast.
"""

import json
from pathlib import Path

import fastf1
import pandas as pd

fastf1.Cache.enable_cache("fastf1_cache")  # avoids re-downloading every run

# Each tuple is (year, race name, leading car's driver code, trailing car's driver code)
RACES_TO_EXTRACT = [
    (2021, "France", "HAM", "VER"),
    (2021, "Hungary", "HAM", "BOT"),
    (2021, "Abu Dhabi", "HAM", "VER"),
]


def pit_loss_for_circuit(laps: pd.DataFrame, driver: str) -> float:
    """
    Estimate pit lane time loss: compare the lap time of the in-lap
    and out-lap against that driver's median clean-air lap time.
    """
    driver_laps = laps.pick_drivers(driver)
    pit_laps = driver_laps[driver_laps["PitInTime"].notna() | driver_laps["PitOutTime"].notna()]
    clean_laps = driver_laps[driver_laps["PitInTime"].isna() & driver_laps["PitOutTime"].isna()]

    if pit_laps.empty or clean_laps.empty:
        return 22.0  # sane fallback if a session has no clean pit-lap data

    median_clean = clean_laps["LapTime"].median().total_seconds()
    median_pit = pit_laps["LapTime"].median().total_seconds()
    return round(median_pit - median_clean, 1)


def deg_per_lap(laps: pd.DataFrame, driver: str) -> float:
    """
    Fit a straight line through (tyre life, lap time) for one stint
    and return the slope - how many seconds slower each lap gets as
    the tyre ages by one lap.
    """
    driver_laps = laps.pick_drivers(driver).pick_quicklaps()
    if driver_laps.empty:
        return 0.08  # fallback

    stint = driver_laps[driver_laps["Stint"] == driver_laps["Stint"].mode()[0]]
    x = stint["TyreLife"].astype(float)
    y = stint["LapTime"].dt.total_seconds()

    if len(x) < 4:
        return 0.08

    slope = pd.Series(y.values).diff().div(pd.Series(x.values).diff()).mean()
    return round(max(slope, 0.0), 3)


def gap_before_pit_window(laps: pd.DataFrame, driver_a: str, driver_b: str, lap_number: int) -> float:
    lap_a = laps.pick_drivers(driver_a).pick_laps(lap_number)
    lap_b = laps.pick_drivers(driver_b).pick_laps(lap_number)
    if lap_a.empty or lap_b.empty:
        return 1.5
    return round(abs((lap_b["Time"].iloc[0] - lap_a["Time"].iloc[0]).total_seconds()), 2)


def extract_race(year: int, race_name: str, driver_a: str, driver_b: str) -> dict:
    session = fastf1.get_session(year, race_name, "R")
    session.load()
    laps = session.laps

    a_pit_lap = int(
        laps.pick_drivers(driver_a)[laps.pick_drivers(driver_a)["PitInTime"].notna()]["LapNumber"].iloc[0]
    )

    return {
        "id": f"{race_name.lower().replace(' ', '')}{year}",
        "label": f"{year} {race_name} Grand Prix",
        "circuit": session.event["EventName"],
        "round": f"Round {session.event['RoundNumber']}",
        "raceLaps": int(laps["LapNumber"].max()),
        "pitLoss": pit_loss_for_circuit(laps, driver_a),
        "degPerLap": deg_per_lap(laps, driver_a),
        "initialGap": gap_before_pit_window(laps, driver_a, driver_b, max(1, a_pit_lap - 5)),
        "rivalPitLap": a_pit_lap,
        "carA": {"name": driver_a, "team": "", "color": "#E8ECF1"},
        "carB": {"name": driver_b, "team": "", "color": "#9D4EDD"},
        "compoundA": "",
        "compoundB": "",
        "trafficZones": [],
        "note": ""
    }


def main():
    races = [extract_race(*r) for r in RACES_TO_EXTRACT]
    out_path = Path(__file__).parent.parent / "data" / "races.js"

    js_content = (
        "// Generated by python/extract_strategy_data.py\n"
        "// Loaded as a plain script (not fetch) so this works even when you\n"
        "// just double-click index.html - no local server required.\n"
        f"window.FAMOUS_RACES = {json.dumps(races, indent=2)};\n"
    )
    out_path.write_text(js_content)
    print(f"Wrote {len(races)} races to {out_path}")


if __name__ == "__main__":
    main()
